package com.jonathan.portfolio.audit;
public enum AuditAction { LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT, PROJECT_CREATE, PROJECT_UPDATE, PROJECT_DUPLICATE, PROJECT_PUBLISH, PROJECT_UNPUBLISH, PROJECT_ARCHIVE, PROJECT_RESTORE, PROJECT_DELETE, PROJECT_REORDER, PROJECT_SLUG_CHANGE, MEDIA_ADD, MEDIA_DELETE, ADMIN_CREATE, ADMIN_PASSWORD_RESET, ADMIN_ENABLE, ADMIN_DISABLE, ADMIN_DELETE }
