import type { Project } from "~/types/api";
export const episort: Project = {
  id: "1",
  title: "Episort",
  slug: "episort",
  shortDescription: "Organize and rename a media library before Plex.",
  fullDescription:
    "A complete and safe application to organize files before importing them into a Plex media library.",
  problem:
    "Organizing a large media library becomes hard once the files are badly named.",
  context: "Mixed folders.",
  objectives: ["Identify"],
  solution: "Analyze, then have a plan confirmed.",
  role: "Full design and development.",
  architecture: "Modular JavaFX application.",
  status: "IN_PROGRESS",
  projectType: "PERSONAL",
  featureLevel: "PRIMARY",
  featured: true,
  displayOrder: 1,
  visibility: "PUBLIC",
  publicationStatus: "PUBLISHED",
  technologies: ["Java", "JavaFX"],
  features: ["Scan"],
  decisions: ["Two-step confirmation"],
  challenges: ["Ambiguities"],
  learnings: ["Explainability"],
  nextSteps: ["Tests"],
  githubUrl: null,
  demoUrl: null,
  seoTitle: null,
  seoDescription: null,
  openGraphImageUrl: null,
  createdAt: "2026-01-01T00:00:00Z",
  updatedAt: "2026-01-01T00:00:00Z",
  publishedAt: "2026-01-01T00:00:00Z",
  archivedAt: null,
  media: [],
  translations: {},
};
