package com.jonathan.portfolio.config;

import com.jonathan.portfolio.project.domain.*;
import com.jonathan.portfolio.project.dto.ProjectWriteRequest;
import com.jonathan.portfolio.project.infrastructure.ProjectRepository;
import java.util.List;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Seeds the case studies shipped with a fresh install. Project content is stored once per project,
 * so this text is the site's source language (English); translated case studies would need a
 * per-locale content table.
 */
@Component @ConditionalOnProperty(name="app.seed.enabled",havingValue="true",matchIfMissing=true)
public class ProjectSeed implements ApplicationRunner {
    private final ProjectRepository projects; public ProjectSeed(ProjectRepository projects){this.projects=projects;}
    @Override @Transactional public void run(ApplicationArguments args){seed(episort());seed(janus());seed(overkill());seed(social());}
    private void seed(ProjectWriteRequest request){if(projects.existsBySlugIgnoreCase(request.slug()))return;var project=new Project(request);project.publish();projects.save(project);}
    private ProjectWriteRequest base(String title,String slug,String shortDescription,String fullDescription,String problem,String context,String solution,String role,String architecture,ProjectStatus status,ProjectType type,FeatureLevel level,int order,List<String> objectives,List<String> technologies,List<String> features,List<String> decisions,List<String> challenges,List<String> learnings,List<String> nextSteps,String seo){return new ProjectWriteRequest(title,slug,shortDescription,fullDescription,problem,context,solution,role,architecture,status,type,level,level==FeatureLevel.PRIMARY,order,Visibility.PUBLIC,objectives,technologies,features,decisions,challenges,learnings,nextSteps,"","",title+" — case study",seo,"");}
    private ProjectWriteRequest episort(){return base("Episort","episort","Organize and rename a media library before importing it into Plex.","Episort is a Windows-first desktop application built with Java and JavaFX. It analyzes show and movie folders, separates safe cases from ambiguous ones, and prepares a reviewable plan before any operation runs.","Organizing a large media library becomes hard once files are badly named, mixed together, or matched to the wrong episode order.","Naming conventions vary, several shows can be mixed in one folder, and broadcast orders do not always line up. Blind automation can therefore damage an entire library.","A deterministic analysis chain classifies the files, enriches them through TVDB, then exposes a manual review. Moving files requires two confirmations and stays journaled so a run can be resumed.","Product design, architecture, Java/JavaFX development, and the safety strategy for file operations.","A desktop application separating scan, analysis, enrichment, plan building, and execution. The interface never moves a file directly.",ProjectStatus.IN_PROGRESS,ProjectType.PERSONAL,FeatureLevel.PRIMARY,1,List.of("Identify media without hiding uncertainty","Prepare a verifiable plan","Keep every destructive operation explicitly confirmed"),List.of("Java","JavaFX","TVDB API"),List.of("Scans AVI, MP4 and MKV","Detects shows, movies, unknown files and ambiguities","Aired, DVD and absolute orders","Manual review","Source-to-destination plan","Two-step confirmation","Journaling and recovery"),List.of("Prefer an explainable result over opaque detection","Keep the plan separate from its execution","Treat ambiguity as a normal state"),List.of("Interpreting inconsistent file names","Handling several mixed release groups","Reconciling different episode orders"),List.of("Safe usage comes from how the flow is structured","Reliable automation has to declare its uncertainty"),List.of("Harden recovery","Broaden naming tests","Add real media"),"A safe JavaFX application to organize and rename a Plex media library.");}
    private ProjectWriteRequest janus(){return base("Janus","janus","Centralize, control, and hand out access to API keys.","Janus explores an admin panel and a backend service that keep API keys out of client applications. The project is ongoing: the target architecture is settled, but not every feature is finished.","API keys tend to be scattered across projects, rotated poorly, and exposed directly to the applications that use them.","More integrations means more secrets, more permissions, and more rotations. Traceability quickly falls short.","A proxy service grants access based on the calling application's identity and permissions, while a dedicated panel handles lifecycle and logs.","Product design, permission modeling, and development of both the backend service and the panel.","A Spring Boot service exposing a REST API, PostgreSQL persistence, and separate Docker Compose environments.",ProjectStatus.IN_PROGRESS,ProjectType.PERSONAL,FeatureLevel.PRIMARY,2,List.of("Centralize secrets","Reduce their exposure","Control which applications are authorized","Make revocation and auditing practical"),List.of("Java","Spring Boot","Spring Security","REST API","PostgreSQL","Docker"),List.of("Centralized storage","Access proxy","Authorized applications","Permissions","Journaling","Revocation"),List.of("Never pass the secret along when it is not needed","Trace accesses without tracing secrets","Design for revocation from the first model"),List.of("Permission model","Separating administration from consumption","Rotation without downtime"),List.of("Secret management is a lifecycle problem","Logs have to stay useful without becoming sensitive"),List.of("Finish the proxy flow","Strengthen authorization tests","Document the production setup"),"A Spring Boot service to centralize and control API keys.");}
    private ProjectWriteRequest overkill(){return base("Overkill","overkill","Aggregate and track job offers across the Paris region.","A team project bringing scattered job offers together, making them easier to compare, and keeping a clear record of applications.","Offers are spread across several platforms, which makes them hard to search, compare, and follow effectively.","The project pairs a React frontend with a Symfony backend around a shared model of offers and application tracking.","A team web application combining a search and tracking interface with an API and a PostgreSQL database.","Full-stack development contribution within a team project.","React/Vite frontend, Symfony API, PostgreSQL, and a Docker environment.",ProjectStatus.COMPLETED,ProjectType.TEAM,FeatureLevel.SECONDARY,3,List.of("Bring offers together","Speed up comparison","Centralize tracking"),List.of("React","Vite","Tailwind CSS","Symfony","PostgreSQL","Docker"),List.of("Offer aggregation","Search","Comparison","Application tracking"),List.of("Share a clear model between frontend and backend","Scope the work to what a team can carry"),List.of("Coordinating contributions","Unifying several sources"),List.of("Good API contracts make collective work easier"),List.of("Add real media","Detail Jonathan's contributions"),"A React and Symfony team project to track job offers in the Paris region.");}
    private ProjectWriteRequest social(){return base("Mini social network","mini-social-network","Grow a full-stack application alongside backend learning.","A learning application built in several versions to experiment with authentication, profiles, posts, and social relationships, with a backend that moved from Laravel to Java along the way.","Understanding a full-stack system means connecting authentication, data, API, and interactions inside one coherent application.","The project is a testing ground for technical evolution. It documents a progression and architecture changes rather than a finished product.","A deliberately small social network, rebuilt several times to compare framework and modeling choices.","Design and development with learning as the goal.","A full-stack architecture that went through several backend iterations, notably Laravel and then Java.",ProjectStatus.COMPLETED,ProjectType.LEARNING,FeatureLevel.SECONDARY,4,List.of("Practice a full-stack flow","Compare several backends","Understand user and content relationships"),List.of("Laravel","Java","REST API"),List.of("Authentication","Profiles","Posts","Interactions","Comments","Social relationships"),List.of("Reuse the same domain to compare approaches","Keep the scope small"),List.of("Evolving the model","Comparing backend trade-offs"),List.of("A rewrite only pays off when the comparison is explicit"),List.of("Document the differences between versions"),"A full-stack learning project built around a mini social network.");}
}
