package com.jonathan.portfolio.config;

import com.jonathan.portfolio.project.domain.*;
import com.jonathan.portfolio.project.dto.ProjectWriteRequest;
import com.jonathan.portfolio.project.infrastructure.ProjectRepository;
import java.util.List;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@Component @ConditionalOnProperty(name="app.seed.enabled",havingValue="true",matchIfMissing=true)
public class ProjectSeed implements ApplicationRunner {
    private final ProjectRepository projects; public ProjectSeed(ProjectRepository projects){this.projects=projects;}
    @Override @Transactional public void run(ApplicationArguments args){seed(episort());seed(janus());seed(overkill());seed(social());}
    private void seed(ProjectWriteRequest request){if(projects.existsBySlugIgnoreCase(request.slug()))return;var project=new Project(request);project.publish();projects.save(project);}
    private ProjectWriteRequest base(String title,String slug,String shortDescription,String fullDescription,String problem,String context,String solution,String role,String architecture,ProjectStatus status,ProjectType type,FeatureLevel level,int order,List<String> objectives,List<String> technologies,List<String> features,List<String> decisions,List<String> challenges,List<String> learnings,List<String> nextSteps,String seo){return new ProjectWriteRequest(title,slug,shortDescription,fullDescription,problem,context,solution,role,architecture,status,type,level,level==FeatureLevel.PRIMARY,order,Visibility.PUBLIC,objectives,technologies,features,decisions,challenges,learnings,nextSteps,"","",title+" — étude de cas",seo,"");}
    private ProjectWriteRequest episort(){return base("Episort","episort","Organiser et renommer une médiathèque avant son intégration dans Plex.","Episort est une application desktop Windows-first en Java et JavaFX. Elle analyse des dossiers de séries et de films, distingue les cas sûrs des ambiguïtés et prépare un plan contrôlable avant toute opération.","Organiser correctement une grande médiathèque devient difficile lorsque les fichiers sont mal nommés, mélangés ou associés au mauvais ordre d’épisodes.","Les conventions varient, plusieurs séries peuvent être mélangées et les ordres de diffusion ne coïncident pas toujours. Une automatisation aveugle peut donc détériorer une bibliothèque entière.","Une chaîne d’analyse déterministe classe les fichiers, complète les informations via TVDB puis expose une revue manuelle. Le déplacement exige deux validations et reste journalisé pour permettre une reprise.","Conception produit, architecture, développement Java/JavaFX et stratégie de sécurisation des opérations fichiers.","Application desktop séparant scan, analyse, enrichissement, construction du plan et exécution. L’interface ne déplace jamais directement un fichier.",ProjectStatus.IN_PROGRESS,ProjectType.PERSONAL,FeatureLevel.PRIMARY,1,List.of("Identifier les médias sans masquer l’incertitude","Préparer un plan vérifiable","Rendre toute opération destructive explicitement contrôlée"),List.of("Java","JavaFX","TVDB API"),List.of("Scan AVI, MP4 et MKV","Détection séries, films, inconnus et ambiguïtés","Ordres aired, DVD et absolute","Revue manuelle","Plan source vers destination","Double validation","Journalisation et récupération"),List.of("Préférer un résultat explicable à une détection opaque","Isoler le plan de l’exécution","Traiter l’ambiguïté comme un état normal"),List.of("Interpréter des noms hétérogènes","Gérer plusieurs groupes mélangés","Réconcilier différents ordres d’épisodes"),List.of("La sécurité d’usage vient de l’architecture du flux","Une automatisation fiable doit déclarer son incertitude"),List.of("Consolider la récupération","Élargir les tests de nommage","Ajouter les médias réels"),"Application JavaFX sécurisée pour organiser et renommer une médiathèque Plex.");}
    private ProjectWriteRequest janus(){return base("Janus","janus","Centraliser, contrôler et distribuer l’accès aux clés API.","Janus explore un panneau d’administration et un service backend qui évitent de disperser les clés API dans les applications clientes. Le projet est en cours : l’architecture cible est définie, toutes les fonctions ne sont pas finalisées.","Les clés API sont souvent dispersées dans différents projets, mal renouvelées et directement exposées aux applications qui les utilisent.","Multiplier les intégrations multiplie aussi les secrets, leurs permissions et les opérations de rotation. La traçabilité devient vite insuffisante.","Un service proxy délivre l’accès selon l’identité et les permissions de l’application ; un panel spécialisé gère cycle de vie et journaux.","Conception du produit, modélisation des permissions et développement du service backend et du panel.","Service Spring Boot exposant une API REST, persistance PostgreSQL et environnements Docker Compose séparés.",ProjectStatus.IN_PROGRESS,ProjectType.PERSONAL,FeatureLevel.PRIMARY,2,List.of("Centraliser les secrets","Réduire leur exposition","Contrôler les applications autorisées","Rendre révocation et audit praticables"),List.of("Java","Spring Boot","Spring Security","API REST","PostgreSQL","Docker"),List.of("Stockage centralisé","Proxy d’accès","Applications autorisées","Permissions","Journalisation","Révocation"),List.of("Ne jamais transmettre inutilement le secret","Tracer les accès sans tracer les secrets","Prévoir la révocation dès le modèle initial"),List.of("Modèle de permissions","Séparation administration et consommation","Rotation sans interruption"),List.of("La gestion des secrets est un problème de cycle de vie","Les journaux doivent rester utiles sans devenir sensibles"),List.of("Finaliser le flux proxy","Renforcer les tests d’autorisation","Documenter la production"),"Service Spring Boot de centralisation et de contrôle des clés API.");}
    private ProjectWriteRequest overkill(){return base("Overkill","overkill","Agréger et suivre des offres d’emploi en Île-de-France.","Projet d’équipe visant à réunir des offres dispersées, faciliter leur comparaison et conserver une trace claire des candidatures.","Les offres sont dispersées sur plusieurs plateformes et deviennent difficiles à rechercher, comparer et suivre efficacement.","Le projet met en commun un frontend React et un backend Symfony autour d’un modèle partagé des offres et du suivi.","Une application web d’équipe combine une interface de recherche et de suivi avec une API et une base PostgreSQL.","Contribution au développement full-stack au sein d’un projet d’équipe.","Frontend React/Vite, API Symfony, PostgreSQL et environnement Docker.",ProjectStatus.COMPLETED,ProjectType.TEAM,FeatureLevel.SECONDARY,3,List.of("Rassembler les offres","Accélérer la comparaison","Centraliser le suivi"),List.of("React","Vite","Tailwind CSS","Symfony","PostgreSQL","Docker"),List.of("Agrégation d’offres","Recherche","Comparaison","Suivi des candidatures"),List.of("Partager un modèle clair entre frontend et backend","Adapter le périmètre au travail d’équipe"),List.of("Coordonner les contributions","Unifier plusieurs sources"),List.of("De bons contrats d’API facilitent le travail collectif"),List.of("Ajouter les médias réels","Préciser les contributions de Jonathan"),"Projet d’équipe React et Symfony pour suivre des offres d’emploi en Île-de-France.");}
    private ProjectWriteRequest social(){return base("Mini réseau social","mini-reseau-social","Faire évoluer une application full-stack au fil des apprentissages backend.","Application d’apprentissage construite en plusieurs versions pour expérimenter authentification, profils, publications et relations sociales, avec un backend passé notamment de Laravel à Java.","Comprendre un système full-stack demande de relier authentification, données, API et interactions dans une application cohérente.","Le projet sert de terrain d’évolution technique. Il documente une progression et des changements d’architecture plutôt qu’un produit final.","Un réseau social volontairement réduit, repris en plusieurs versions pour confronter les choix de framework et de modélisation.","Conception et développement dans un objectif d’apprentissage.","Architecture full-stack ayant connu plusieurs itérations backend, notamment Laravel puis Java.",ProjectStatus.COMPLETED,ProjectType.LEARNING,FeatureLevel.SECONDARY,4,List.of("Pratiquer un flux full-stack","Comparer plusieurs backends","Comprendre les relations utilisateurs/contenus"),List.of("Laravel","Java","API REST"),List.of("Authentification","Profils","Publications","Interactions","Commentaires","Relations sociales"),List.of("Reprendre le même domaine pour comparer les approches","Conserver un périmètre réduit"),List.of("Faire évoluer le modèle","Comparer les compromis backend"),List.of("Réécrire n’est utile que si la comparaison est explicite"),List.of("Documenter les différences entre versions"),"Projet d’apprentissage full-stack autour d’un mini réseau social.");}
}
