import { zodResolver } from "@hookform/resolvers/zod";
import { LockKeyhole } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { redirect,useNavigate,type LoaderFunctionArgs, type MetaFunction } from "react-router";
import { z } from "zod";
import { ThemeToggle } from "~/components/theme-toggle";
import { ApiRequestError,apiLoader,apiMutation,resetCsrf } from "~/lib/api";
import type { Session } from "~/types/api";

const schema=z.object({email:z.email("Saisissez une adresse e-mail valide."),password:z.string().min(1,"Le mot de passe est obligatoire.").max(200)});type Values=z.infer<typeof schema>;
export const meta:MetaFunction=()=>[{title:"Connexion — Administration"},{name:"robots",content:"noindex,nofollow"}];
export async function loader({request}:LoaderFunctionArgs){const session=await apiLoader<Session>(request,"/auth/session");if(session.authenticated)throw redirect("/admin");return null}
export default function AdminLogin(){const navigate=useNavigate();const [serverError,setServerError]=useState("");const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schema)});async function submit(values:Values){setServerError("");try{resetCsrf();await apiMutation<Session>("/auth/login",{method:"POST",body:JSON.stringify(values)});await navigate("/admin")}catch(error){setServerError(error instanceof ApiRequestError?error.payload.message:"Connexion impossible. Réessayez.")}}return <main id="main-content" className="login-page"><section className="login-panel" aria-labelledby="login-title"><div className="flex items-center justify-between"><span className="wordmark"><span className="wordmark-mark" aria-hidden/>Administration</span><ThemeToggle/></div><h1 id="login-title">Connexion</h1><p>Accès réservé à Jonathan. Aucune inscription publique n’est proposée.</p><form className="login-form" onSubmit={(event)=>void handleSubmit(submit)(event)} noValidate>{serverError&&<p className="form-error" role="alert">{serverError}</p>}<div className="field"><label htmlFor="email">Adresse e-mail</label><input className="input" id="email" type="email" autoComplete="username" aria-invalid={!!errors.email} aria-describedby={errors.email?"email-error":undefined} {...register("email")}/>{errors.email&&<span id="email-error" className="field-error">{errors.email.message}</span>}</div><div className="field"><label htmlFor="password">Mot de passe</label><input className="input" id="password" type="password" autoComplete="current-password" aria-invalid={!!errors.password} aria-describedby={errors.password?"password-error":undefined} {...register("password")}/>{errors.password&&<span id="password-error" className="field-error">{errors.password.message}</span>}</div><button className="button button-primary" disabled={isSubmitting}>{isSubmitting?"Connexion…":<><LockKeyhole size={17} aria-hidden/>Se connecter</>}</button></form></section></main>}
